# AUTOMATICALLY UPDATED FILE: EDIT WITH CAUTION!
VERSION = (0, 1, 0)
DEBUG = False

# AUTOMATICALLY-GENERATED CONTENT FOLLOWS; DO NOT EDIT MANUALLY!
BUILD_NUMBER = 4
BUILD_TIME = 1423496285
BUILD_MACHINE = 'DEDHAM'
