# AUTOMATICALLY UPDATED FILE: EDIT WITH CAUTION!
VERSION = (1, 0, 0)
DEBUG = False

# AUTOMATICALLY-GENERATED CONTENT FOLLOWS; DO NOT EDIT MANUALLY!
BUILD_NUMBER = 5
BUILD_TIME = 1423595778
BUILD_MACHINE = 'DEDHAM'
