# install and run are the same commands
before_install:
  - python --version
install:
  - pip install .[test]
script:
  - python -m pytest ./testing/ --cov=idelib
  - sphinx-build -W -b html docs/source docs/html
after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  include:
    # Windows doesn't support native python yet, so here we are - 3.6
    - os: windows
      language: shell
      env: PATH=/c/python36:/c/Python36/scripts:$PATH
      before_install:
        - choco install python3 --version=3.6.8
        - python -m pip install virtualenv
        - virtualenv $HOME/venv
        - source $HOME/venv/Scripts/activate
    # Windows doesn't support native python yet, so here we are - 3.7
    - os: windows
      language: shell
      env: PATH=/c/python37:/c/Python37/scripts:$PATH
      before_install:
        - choco install python3 --version=3.7.9
        - python -m pip install virtualenv
        - virtualenv $HOME/venv
        - source $HOME/venv/Scripts/activate
    # Windows doesn't support native python yet, so here we are - 3.8
    - os: windows
      language: shell
      env: PATH=/c/python38:/c/Python38/scripts:$PATH
      before_install:
        - choco install python3 --version=3.8.10
        - python -m pip install virtualenv
        - virtualenv $HOME/venv
        - source $HOME/venv/Scripts/activate
    # Windows doesn't support native python yet, so here we are - 3.9
    - os: windows
      language: shell
      env: PATH=/c/python39:/c/Python39/scripts:$PATH
      before_install:
        - choco install python3 --version=3.9.5
        - python -m pip install virtualenv
        - virtualenv $HOME/venv
        - source $HOME/venv/Scripts/activate
  allow_failures:
    - if: env(ALLOW_FAILURES)=TRUE

# Linux is so much more cooperative
os: linux
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

