# AUTOMATICALLY UPDATED FILE: EDIT WITH CAUTION!
VERSION = (1, 3, 0)
DEBUG = True
BETA = True

# AUTOMATICALLY-GENERATED CONTENT FOLLOWS; DO NOT EDIT MANUALLY!
BUILD_NUMBER = 151
BUILD_TIME = 1430509352
BUILD_MACHINE = 'DEDHAM'
