# AUTOMATICALLY UPDATED FILE: EDIT WITH CAUTION!
VERSION = (1, 4, 0)
DEBUG = True
BETA = True

# AUTOMATICALLY-GENERATED CONTENT FOLLOWS; DO NOT EDIT MANUALLY!
BUILD_NUMBER = 171
BUILD_TIME = 1436803000
BUILD_MACHINE = 'DEDHAM'
