# AUTOMATICALLY UPDATED FILE: EDIT WITH CAUTION!
VERSION = (1, 7, 0)
DEBUG = True

# AUTOMATICALLY-GENERATED CONTENT FOLLOWS; DO NOT EDIT MANUALLY!
BUILD_NUMBER = 15
BUILD_TIME = 1471380478
BUILD_MACHINE = 'DEDHAM'
