# AUTOMATICALLY UPDATED FILE: EDIT WITH CAUTION!
VERSION = (0, 0, 1)
DEBUG = True

# AUTOMATICALLY-GENERATED CONTENT FOLLOWS; DO NOT EDIT MANUALLY!
BUILD_NUMBER = 0
BUILD_TIME = 1413493175
BUILD_MACHINE = 'DEDHAM'
