# AUTOMATICALLY UPDATED FILE: EDIT WITH CAUTION!
VERSION = (1, 8, 0)
DEBUG = False

# AUTOMATICALLY-GENERATED CONTENT FOLLOWS; DO NOT EDIT MANUALLY!
BUILD_NUMBER = 19
BUILD_TIME = 1521038707
BUILD_MACHINE = 'DEDHAM'
