# AUTOMATICALLY UPDATED FILE: EDIT WITH CAUTION!
VERSION = (1, 8, 0)
DEBUG = True

# AUTOMATICALLY-GENERATED CONTENT FOLLOWS; DO NOT EDIT MANUALLY!
BUILD_NUMBER = 18
BUILD_TIME = 1518039954
BUILD_MACHINE = 'DEDHAM'
