# AUTOMATICALLY UPDATED FILE: EDIT WITH CAUTION!
VERSION = (0, 1, 0)
DEBUG = True

# AUTOMATICALLY-GENERATED CONTENT FOLLOWS; DO NOT EDIT MANUALLY!
BUILD_NUMBER = 4
BUILD_TIME = 1429625938
BUILD_MACHINE = 'DEDHAM'
