# AUTOMATICALLY UPDATED FILE: EDIT WITH CAUTION!
VERSION = (1, 4, 0)
DEBUG = True

# AUTOMATICALLY-GENERATED CONTENT FOLLOWS; DO NOT EDIT MANUALLY!
BUILD_NUMBER = 11
BUILD_TIME = 1468339053
BUILD_MACHINE = 'DEDHAM'
