name: Test on any push, with lots of OS support


on: push


jobs:
  unit-tests:
    name: Run Unit Tests

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install --upgrade pip

      - uses: actions/checkout@v2

      - run: python -m pip install .[test]

      - run: python -m pytest ./testing/ --cov=idelib
      - run: sphinx-build -W -b html docs/source docs/html
      - run: sphinx-build -W -b doctest docs/source docs/doctest
